src/AdminSite/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MusicStoreDemo.AdminSite.Models;
using MusicStoreDemo.AdminSite.Models.AlbumViewModels;
using MusicStoreDemo.AdminSite.Models.Enums;
using MusicStoreDemo.AdminSite.Models.GenreViewModels;
using MusicStoreDemo.AdminSite.Models.Mappers;
using MusicStoreDemo.Common.Models.Album;
using MusicStoreDemo.Common.Models.Artist;
using MusicStoreDemo.Common.Models.Enum;
using MusicStoreDemo.Common.Models.Image;
using MusicStoreDemo.Common.Repositories;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MusicStoreDemo.AdminSite.Controllers
{
	[Authorize(Policy = "isAdmin")]
    public class AlbumController : Controller
    {
        private const int _pageSize = 24;

        private readonly IAlbumRepository _albumRepo;
		private readonly IAlbumGroupRepository _albumGroupRepo;
        private readonly IArtistRepository _artistRepo;
        private readonly IImageRepository _imageRepo;
        private readonly IGenreRepository _genreRepo;

        public AlbumController(
			IAlbumRepository albumRepo,
            IAlbumGroupRepository albumGroupRepo,
            IArtistRepository artistRepo, 
            IGenreRepository genreRepo, 
            IImageRepository imageRepo)
        {
            _albumRepo = albumRepo;
			_albumGroupRepo = albumGroupRepo;
            _artistRepo = artistRepo;
            _imageRepo = imageRepo;
            _genreRepo = genreRepo;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery]int page = 0, PublishStatus? status = null)
        {
            AlbumIndexViewModel model = new AlbumIndexViewModel();
            page = Math.Max(page, 0);
            PublishStatus flags = PublishStatus.PUBLISHED | PublishStatus.UNPUBLISHED;
            if (status.HasValue)
            {
                flags = status.Value;
            }
            var result = await _albumRepo.ListAsync(page, _pageSize, flags);
            model.PageIndex = result.PageIndex;
            model.PageSize = result.PageSize;
            model.TotalPages = (int)Math.Ceiling(((double)result.TotalItems / (double)result.PageSize));

            AlbumViewModelMapper mapper = new AlbumViewModelMapper();
            model.Items.AddRange(result.Items.Select(i => mapper.Map(i)));

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            CreateAlbumViewModel model = new CreateAlbumViewModel();
            var genresResult = await _genreRepo.ListAsync(contentPublicationFlags: PublishStatus.PUBLISHED);
            model.Genres = genresResult.Genres.Select(g => new SelectableGenreViewModel
            {
                Name = g.Name,
                IsSelected = false
            }).ToList();
			var allGroups = await _albumGroupRepo.ListAsync();
			model.Groups = allGroups.Select(x => new CheckBoxListItem { Label = x.Name, Value = x.Key, IsSelected = false }).ToList();
            PublishStatus flags = PublishStatus.PUBLISHED | PublishStatus.UNPUBLISHED;
            model.ArtistOptions = (await _artistRepo.ListNamesAsync(flags)).Select(x => 
                new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString(),
                    Selected = x.Id == model.ArtistId
                }
            ).ToList();
			
            model.Tracks = new List<AlbumTrackViewModel>();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateAlbumViewModel model)
        {
            AlbumViewModelMapper mapper = new AlbumViewModelMapper();
            PublishStatus flags = PublishStatus.PUBLISHED | PublishStatus.UNPUBLISHED;
            var artistNames = await _artistRepo.ListNamesAsync(flags);
            model.ArtistOptions = artistNames
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString(),
                    Selected = x.Id == model.ArtistId
                }).ToList();
			List<CheckBoxListItem> groupOptions = (await _albumGroupRepo.ListAsync())
                    .Select(x => new CheckBoxListItem
                    {
                        Label = x.Name,
                        Value = x.Key,
                        IsSelected = model.Groups.Any(grp => grp.IsSelected && grp.Value == x.Key)
                    }).ToList();
            model.Groups = groupOptions;

            if (ModelState.IsValid)
            {
                int? createdImageId = null;
                if (model.CoverImage != null && model.CoverImage.Length > 0)
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        await model.CoverImage.CopyToAsync(ms);
                        ImageReferenceDetail imageRef = await _imageRepo.AddAsync(new ImageReferenceDetail
                        {
                            Data = ms.ToArray(),
                            FileName = model.CoverImage.FileName,
                            MimeType = model.CoverImage.ContentType
                        });
                        if (imageRef != null)
                        {
                            createdImageId = imageRef.Id;
                        }
                    }
                }


                var result = await _albumRepo.AddAsync(mapper.Map(model, createdImageId));

				await _albumGroupRepo.SetGroupsForAlbum(result.Id, model.Groups.Where(g => g.IsSelected).Select(g => g.Value).ToList());

                this.SetBootstrapPageAlert("Success", "Album added", BootstrapAlertType.success);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            AlbumViewModelMapper mapper = new AlbumViewModelMapper();
            EditAlbumViewModel model = new EditAlbumViewModel();
           

            var genresResult = await _genreRepo.ListAsync(contentPublicationFlags: PublishStatus.PUBLISHED);
            
			var allGroups = await _albumGroupRepo.ListAsync();
			var albumGroupKeys = (await _albumGroupRepo.GetGroupsForAlbum(id)).Select(x => x.Key);


            AlbumDetail album = await _albumRepo.GetAsync(id);
            if (album != null)
            {
                PublishStatus flags = PublishStatus.PUBLISHED | PublishStatus.UNPUBLISHED;
                ICollection<ArtistNameRef> artistNames = await _artistRepo.ListNamesAsync(flags);
                model = mapper.Map(album, artistNames, genresResult.Genres);
				model.Groups = allGroups.Select(x => new CheckBoxListItem
                {
                    Label = x.Name,
                    Value = x.Key,
                    IsSelected = (albumGroupKeys.Contains(x.Key))
                }).ToList();

                return View(model);
            }
            else
            {
                // todo: show error message
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditAlbumViewModel model)
        {
            AlbumViewModelMapper mapper = new AlbumViewModelMapper();
            PublishStatus flags = PublishStatus.PUBLISHED | PublishStatus.UNPUBLISHED;
            var artistNames = await _artistRepo.ListNamesAsync(flags);
            model.ArtistOptions = artistNames
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString(),
                    Selected = x.Id == model.ArtistId
                }).ToList();

			List<CheckBoxListItem> groupOptions = (await _albumGroupRepo.ListAsync())
				.Select( x => new CheckBoxListItem { 
				Label = x.Name, 
				Value = x.Key, 
				IsSelected = model.Groups.Any(grp => grp.IsSelected && grp.Value == x.Key)
			}).ToList();
			model.Groups = groupOptions;


            AlbumDetail album = await _albumRepo.GetAsync(model.Id);
            if (album != null)
            {
                // set non postback properties 
                model.CoverImageId = album.CoverImageId;
                model.Created = album.CreatedUtc;
                model.Updated = album.UpdatedUtc;
                model.PublishedStatus = album.PublishedStatus;
                if (ModelState.IsValid)
                {
                    int? createdCoverImageId = null;
                    if (model.CoverImage != null && model.CoverImage.Length > 0)
                    {
                        using (MemoryStream ms = new MemoryStream())
                        {
                            await model.CoverImage.CopyToAsync(ms);
                            ImageReferenceDetail imageRef = await _imageRepo.AddAsync(new ImageReferenceDetail
                            {
                                Data = ms.ToArray(),
                                FileName = model.CoverImage.FileName,
                                MimeType = model.CoverImage.ContentType
                            });
                            if (imageRef != null)
                            {
                                createdCoverImageId = imageRef.Id;
                            }
                        }
                    }

                    album = mapper.MapOnTo(model, album, createdCoverImageId);
                    await _albumRepo.UpdateAsync(album.Id, album);
					await _albumGroupRepo.SetGroupsForAlbum(model.Id, model.Groups.Where(g => g.IsSelected).Select(g => g.Value).ToList());

src/AdminSite/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MusicStoreDemo.AdminSite.Models.Enums;
using MusicStoreDemo.AdminSite.Models.GenreViewModels;
using MusicStoreDemo.AdminSite.Models.Mappers;
using MusicStoreDemo.Common.Models.Enum;
using MusicStoreDemo.Common.Models.Genre;
using MusicStoreDemo.Common.Repositories;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MusicStoreDemo.AdminSite.Controllers
{
	[Authorize(Policy = "isAdmin")]
    public class GenreController : Controller
    {
        private readonly IGenreRepository _genreRepo;
        private readonly ILogger<GenreController> _logger;

        public GenreController(IGenreRepository genreRepo, ILogger<GenreController> logger)
        {
            _genreRepo = genreRepo;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            GenreViewModelMapper mapper = new GenreViewModelMapper();
            GenreIndexPageViewModel model = new GenreIndexPageViewModel();
            //GenreList genres = await _genreRepo.ListAsync(PublishStatus.UNPUBLISHED|PublishStatus.PUBLISHED|PublishStatus.ARCHIVED);
            GenreList genres = await _genreRepo.ListAsync();
            model.Genres = genres.Genres.Select(x => mapper.MapToViewModel(x)).ToList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(new CreateGenreViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateGenreViewModel model)
        {
            if (ModelState.IsValid)
            {
                GenreDetail existingGenre = await _genreRepo.GetAsync(model.Name);
                if (existingGenre == null)
                {
                    try
                    {
                        await _genreRepo.AddAsync(model.Name);
                        this.SetBootstrapPageAlert("Success", "New genre added", BootstrapAlertType.success);
                        return RedirectToAction(nameof(Index));
                    }catch(Exception e)
                    {
                        _logger.LogError(e, "Error creating genre");
                        ModelState.AddModelError(nameof(model.Name), "Error adding genre to the database");
                        return View(model);
                    }
                }
                else
                {
                    ModelState.AddModelError(nameof(model.Name), "A genre with this name already exists");
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Remove(string name)
        {
            GenreViewModelMapper mapper = new GenreViewModelMapper();
            GenreDetail existingGenre = await _genreRepo.GetAsync(name);
            GenreItemViewModel model = mapper.MapToViewModel(existingGenre);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Remove(GenreItemViewModel model)
        {
            GenreViewModelMapper mapper = new GenreViewModelMapper();
            try
            {
                await _genreRepo.DeleteAsync(model.Name);
                this.SetBootstrapPageAlert("Success", $"Deleted genre '{model.Name}' from the database", BootstrapAlertType.success);
                return RedirectToAction(nameof(Index));
            }catch(Exception e)
            {
                _logger.LogError(e, "Error deleting genre");
                ModelState.AddModelError(nameof(model.Name), "Error deleting genre from the database");
                GenreDetail existingGenre = await _genreRepo.GetAsync(model.Name);
                model = mapper.MapToViewModel(existingGenre);
            }
            return View(model);
        }
    }
}

src/AdminSite/Views/Shared/_Layout.cshtml
@using Newtonsoft.Json;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MusicStore admin</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/site-styles.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/libs/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site-styles.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MusicStoreDemo.AdminSite</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Album" asp-action="Index">Albums</a></li>
                    <li><a asp-area="" asp-controller="Artist" asp-action="Index">Artists</a></li>
                    <li><a asp-area="" asp-controller="Genre" asp-action="Index">Genres</a></li>
                    <li><a asp-area="" asp-controller="AlbumGroup" asp-action="Index">Album groups</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (TempData.ContainsKey("pageAlertMessage"))
        {
            // todo:  clean this up in a partial
            var alertModelJson = TempData["pageAlertMessage"] as string;
            BootstrapPageAlertViewModel alertModel = null;
            if (alertModelJson != null)
            {
                try {
                    alertModel = JsonConvert.DeserializeObject<BootstrapPageAlertViewModel>(alertModelJson);
                    <div class="container">
                        <div class="alert alert-@alertModel.AlertType alert-dismissible show" role="alert">
                            @if (!string.IsNullOrWhiteSpace(alertModel.Title)) { <strong>@alertModel.Title</strong> }
                           <span>@alertModel.Message</span>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                }
                catch { }
            }
        }

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MusicStoreDemo.AdminSite</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/libs/jquery/jquery.js"></script>
        <script src="~/libs/bootstrap/js/bootstrap.js"></script>
        <script src="~/libs/handlebars/handlebars.min.js"></script>
        <script src="~/libs/html5sortable/html5sortable.min.js"></script>
        <script src="~/js/compiled/app-libs.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/libs/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/libs/bootstrap/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/libs/handlebars/handlebars.min.js"></script>
        <script src="~/libs/html5sortable/html5sortable.min.js"></script>
        <script src="~/js/compiled/app-libs.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>