src/AdminSite/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MusicStoreDemo.AdminSite.Models.ArtistViewModels;
using MusicStoreDemo.AdminSite.Models.GenreViewModels;
using MusicStoreDemo.Common.Models.Artist;
using MusicStoreDemo.Common.Models.Image;
using MusicStoreDemo.Common.Repositories;
using MusicStoreDemo.Database.Entities;
using System.Collections;
using MusicStoreDemo.AdminSite.Models.Enums;
using MusicStoreDemo.Common.Models.Enum;
using MusicStoreDemo.AdminSite.Models.Mappers;

namespace MusicStoreDemo.AdminSite.Controllers
{
    [Authorize(Policy = "isAdmin")]
    public class ArtistController : Controller
    {
        private const int _pageSize = 24;

        private readonly IArtistRepository _artistRepo;
        private readonly IImageRepository _imageRepo;
        private readonly IGenreRepository _genreRepo;

        public ArtistController(IArtistRepository artistRepo, IGenreRepository genreRepo, IImageRepository imageRepo)
        {
            _artistRepo = artistRepo;
            _imageRepo = imageRepo;
            _genreRepo = genreRepo;
        }

        public async Task<IActionResult> Index([FromQuery]int page = 0, PublishStatus? status = null)
        {
            ArtistIndexViewModel model = new ArtistIndexViewModel();
            page = Math.Max(page, 0);
            PublishStatus flags = PublishStatus.PUBLISHED | PublishStatus.UNPUBLISHED;
            if (status.HasValue)
            {
                flags = status.Value;
            }
            var result = await _artistRepo.ListAsync(page, _pageSize, flags);
            model.PageIndex = result.PageIndex;
            model.PageSize = result.PageSize;
            model.TotalPages = (int)Math.Ceiling(((double)result.TotalItems / (double)result.PageSize));

            ArtistViewModelMapper mapper = new ArtistViewModelMapper();
            model.Items.AddRange(result.Items.Select(i => mapper.Map(i)));
            
            return View(model);
        }

        public async Task<IActionResult> Details([FromQuery]int id)
        {
            Artist artist = await _artistRepo.GetAsync(id);
            if (artist != null)
            {
                return View(new ArtistDetailsViewModel
                {
                    Artist = artist
                });
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            CreateArtistViewModel model = new CreateArtistViewModel();
            var genresResult = await _genreRepo.ListAsync(contentPublicationFlags: PublishStatus.PUBLISHED);
            model.Genres = genresResult.Genres.Select(g => new SelectableGenreViewModel
            {
                Name = g.Name,
                IsSelected = false
            }).ToList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateArtistViewModel model)
        {
            if (ModelState.IsValid)
            {
                int? createdBioImageId = null;
                if(model.BioImage != null && model.BioImage.Length > 0)
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        await model.BioImage.CopyToAsync(ms);
                        ImageReferenceDetail imageRef = await _imageRepo.AddAsync(new ImageReferenceDetail
                        {
                            Data = ms.ToArray(),
                            FileName = model.BioImage.FileName,
                            MimeType = model.BioImage.ContentType
                        });
                        if(imageRef != null)
                        {
                            createdBioImageId = imageRef.Id;
                        }
                    }
                }

                var result = await _artistRepo.AddAsync(new Artist
                {
                    PublishedStatus = PublishStatus.UNPUBLISHED,
                    Name = model.Name,
                    BioText = model.BioText,
                    Genres = model.Genres.Where(g => g.IsSelected).Select(g => g.Name).ToList(),
                    BioImageId = createdBioImageId
                });
                this.SetBootstrapPageAlert("Success", "Artist added", BootstrapAlertType.success);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            EditArtistViewModel model = new EditArtistViewModel();
            var genresResult = await _genreRepo.ListAsync(contentPublicationFlags: PublishStatus.PUBLISHED);
            model.Genres = genresResult.Genres.Select(g => new SelectableGenreViewModel
            {
                Name = g.Name,
                IsSelected = false
            }).ToList();

            ArtistDetail artist = await _artistRepo.GetAsync(id);
            if(artist != null)
            {
                model.Id = artist.Id;
                model.Name = artist.Name;
                model.BioText = artist.BioText;
                model.BioImageId = artist.BioImageId;
                model.Created = artist.CreatedUtc;
                model.Updated = artist.UpdatedUtc;
                model.PublishedStatus = artist.PublishedStatus;
                model.Genres.Where(g => artist.Genres.Contains(g.Name)).ToList().ForEach(x => x.IsSelected = true);
               
                return View(model);
            }
            else
            {
                // todo: show error message
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditArtistViewModel model)
        {
            ArtistDetail artist = await _artistRepo.GetAsync(model.Id);
            if (artist != null)
            {
                // set non postback properties 
                model.BioImageId = artist.BioImageId;
                model.Created = artist.CreatedUtc;
                model.Updated = artist.UpdatedUtc;
                model.PublishedStatus = artist.PublishedStatus;
                if (ModelState.IsValid)
                {
                    int? createdBioImageId = null;
                    if (model.BioImage != null && model.BioImage.Length > 0)
                    {
                        using (MemoryStream ms = new MemoryStream())
                        {
                            await model.BioImage.CopyToAsync(ms);
                            ImageReferenceDetail imageRef = await _imageRepo.AddAsync(new ImageReferenceDetail
                            {
                                Data = ms.ToArray(),
                                FileName = model.BioImage.FileName,
                                MimeType = model.BioImage.ContentType
                            });
                            if (imageRef != null)
                            {
                                createdBioImageId = imageRef.Id;
                            }
                        }
                    }

                    artist.Name = model.Name;
                    artist.BioText = model.BioText;
                    artist.UpdatedUtc = DateTime.UtcNow;
                    artist.Genres = model.Genres.Where(g => g.IsSelected).Select(g => g.Name).ToList();
                    if (createdBioImageId.HasValue)
                    {
                        artist.BioImageId = createdBioImageId.Value;
                    }
                    await _artistRepo.UpdateAsync(artist.Id, artist);
                    this.SetBootstrapPageAlert("Success", "Artist updated", BootstrapAlertType.success);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(model);
                }
            }
            else
            {
                // todo: show error message
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            ArtistDetail artist = await _artistRepo.GetAsync(id);
            if (artist != null)
            {
                artist.PublishedStatus = PublishStatus.DELETED;
                await _artistRepo.UpdateAsync(artist.Id, artist);
                this.SetBootstrapPageAlert("Success", "Artist deleted", BootstrapAlertType.success);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                this.SetBootstrapPageAlert("Error", "Artist was not deleted", BootstrapAlertType.danger);
                return RedirectToAction(nameof(Index));
            }
        }

    }
}

src/AdminSite/Views/Artist/Add.cshtml
@model CreateArtistViewModel
@{
    ViewData["Title"] = "Add artist";
}

<h2>Add artist</h2>


<form asp-action="Add" asp-controller="Artist" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
        <label asp-for="@Model.Name" class=" col-md-2 col-form-label">Name</label>
        <div class="col-md-10">
            <input asp-for="@Model.Name" placeholder="Artist name" />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="@Model.BioText" class=" col-md-2 col-form-label">Bio</label>
        <div class="col-md-10">
            <textarea asp-for="@Model.BioText" placeholder="Bio text" class="form-control"></textarea>
            <span asp-validation-for="@Model.BioText" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="@Model.Genres" class="col-form-label col-md-2 ">Genres</label>
        <div class="col-md-10">
            @for (int i = 0; i < Model.Genres.Count; i++)
            {
                <label class="checkbox-inline">
                    <input type="checkbox" asp-for="@Model.Genres[i].IsSelected" class="form-check-input" />
                    <input type="hidden" asp-for="@Model.Genres[i].Name" />
                    <span class="control-label">@Model.Genres[i].Name</span>
                </label>
            }
        </div>
        <span asp-validation-for="@Model.Genres" class="text-danger"></span>
    </div>

    <div class="form-group row">
        <label asp-for="@Model.BioImage" class="col-md-2 col-form-label">Bio image</label>
        <div class="col-md-10">
            <input type="file" class="form-control" asp-for="@Model.BioImage" style="height: auto;" />
            <span asp-validation-for="@Model.BioImage" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2"></div>
        <div class="col-md-10">
            <button type="submit" class="btn btn-primary">Add artist</button>
            <a asp-action="index" class="btn btn-default">Cancel</a>
        </div>
    </div>
</form>

src/AdminSite/Views/Artist/Details.cshtml
@model ArtistDetailsViewModel
@{
    ViewData["Title"] = "Details";
}

<h2>Artist details</h2>

src/AdminSite/Views/Artist/Edit.cshtml
@model EditArtistViewModel
@{
    ViewData["Title"] = "Edit artist";
}

<h2>Update artist</h2>


<form asp-action="Edit" asp-controller="Artist" enctype="multipart/form-data">

    <input type="hidden" asp-for="@Model.Id" />

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
        <label asp-for="@Model.Name" class=" col-md-2 col-form-label">Name</label>
        <div class="col-md-10">
            <input asp-for="@Model.Name" placeholder="Artist name" />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="@Model.BioText" class=" col-md-2 col-form-label">Bio</label>
        <div class="col-md-10">
            <textarea asp-for="@Model.BioText" placeholder="Bio text" class="form-control"></textarea>
            <span asp-validation-for="@Model.BioText" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="@Model.Genres" class="col-form-label col-md-2 ">Genres</label>
        <div class="col-md-10">
            @for (int i = 0; i < Model.Genres.Count; i++)
            {
                <label class="checkbox-inline">
                    <input type="checkbox" asp-for="@Model.Genres[i].IsSelected" class="form-check-input" />
                    <input type="hidden" asp-for="@Model.Genres[i].Name" />
                    <span class="control-label">@Model.Genres[i].Name</span>
                </label>
            }
        </div>
        <span asp-validation-for="@Model.Genres" class="text-danger"></span>
    </div>

    <div class="form-group row">
        <label asp-for="@Model.BioImage" class="col-md-2 col-form-label">Bio image</label>
        <div class="col-md-10">
            <input type="file" class="form-control" asp-for="@Model.BioImage" style="height: auto;" />
            <span asp-validation-for="@Model.BioImage" class="text-danger"></span>
            @if (Model.BioImageId.HasValue)
            {
                <img class="img-thumbnail" src="http://localhost:5601/api/image/@Model.BioImageId.Value" />
            }
        </div>
        
    </div>
    <div class="form-group row">
        <div class="col-md-2"></div>
        <div class="col-md-10">
            <button type="submit" class="btn btn-primary">Update artist</button>
        </div>
    </div>
</form>

src/AdminSite/Views/Artist/Index.cshtml
@model ArtistIndexViewModel
@{
    ViewData["Title"] = "Manage artists";
}

<div class="container page-header-container">
    <div class="row">
        <div class="col-md-8">
            <h2>Manage artists</h2>
        </div>
        <div class="col-md-4">
            <a asp-action="Add" class="btn btn-primary pull-right">Add artist</a>
        </div>
    </div>
</div>



<div class="container index-list">
    <div class="row header">
        <div class="col-md-4">Name</div>
        <div class="col-md-2">Updated</div>
        <div class="col-md-2">Status</div>
        <div class="col-md-4"></div>
    </div>
    @foreach(var a in Model.Items)
    {
    <div class="row">
        <div class="col-md-4">@a.Name</div>
        <div class="col-md-2">@a.Updated</div>
        <div class="col-md-2">@(a.Status.HasValue ? a.Status.Value.ToString() : "unknown")</div>
        <div class="col-md-4">
            <div class="action-links">
                <a asp-action="edit" asp-route-id="@a.Id" class="btn btn-primary btn-xs">edit</a>
                <button type="submit" class="btn btn-danger btn-xs" asp-action="Delete" asp-route-id="@a.Id">delete</button>
            </div>
        </div>
    </div>
    }
</div>

@if(Model.TotalPages > 1){
<div class="container">
    <div class="row">
        <div class="col">
            <div class="text-center">
                <ul class="pagination">
                    <li class="@(Model.PageIndex == 0 ? "disabled" : "")">
                        <a asp-action="Index" asp-controller="Artist" asp-route-page="0">&laquo;</a>
                    </li>
                    @for(int i = 0; i < Model.TotalPages; i++){
                        
                        <li class="@(i==Model.PageIndex ? "active":"")">
                            <a asp-action="Index" asp-controller="Artist" asp-route-page="@i+1">@(i+1)</a>
                        </li>
                    }
                    <li class="@(Model.PageIndex == Model.TotalPages -1 ? "disabled" : "")">
                        <a asp-action="Index" asp-controller="Artist" asp-route-page="@Model.TotalPages-1">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
}