src/AdminSite/Models/AlbumGroupViewModels/AlbumGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicStoreDemo.AdminSite.Models.AlbumGroupViewModels
{
    public class AlbumGroupViewModel
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public int TotalAlbums { get; set; }
        public DateTime Created { get; set; }
        public DateTime Updated { get; set; }
    }
}

src/AdminSite/Controllers/AlbumGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MusicStoreDemo.AdminSite.Models.AlbumGroupViewModels;
using MusicStoreDemo.AdminSite.Models.Enums;
using MusicStoreDemo.AdminSite.Models.Mappers;
using MusicStoreDemo.Common.Models.AlbumGroup;
using MusicStoreDemo.Common.Repositories;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MusicStoreDemo.AdminSite.Controllers
{
    [Authorize(Policy = "isAdmin")]
    public class AlbumGroupController : Controller
    {
        
        private readonly IAlbumGroupRepository _albumGroupRepo;
        
        private readonly ILogger<AlbumGroupController> _log;
        private readonly AlbumGroupViewModelMapper _mapper;
        public AlbumGroupController(IAlbumGroupRepository albumGroupRepo, ILogger<AlbumGroupController> log)
        {
            _albumGroupRepo = albumGroupRepo;
            _log = log;
            _mapper = new AlbumGroupViewModelMapper();
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ICollection<AlbumGroupDetail> result = await _albumGroupRepo.ListAsync();
            AlbumGroupIndexPageViewModel model = new AlbumGroupIndexPageViewModel();
            model.Items = result.Select(x => _mapper.Map(x)).ToList();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Reorder(int id)
        {
            ReorderAlbumGroupViewModel model = new ReorderAlbumGroupViewModel();
            model.GroupId = id;
            AlbumGroupDetail group = await _albumGroupRepo.GetAsync(id);
            AlbumGroupItemPositionListResult itemsResult = await _albumGroupRepo.GetOrderedAlbumListAsync(id);
            model.GroupName = group.Name;
            model.Items = itemsResult.Items.Select(x=> new ReorderAlbumGroupItemViewModel
            {
                AlbumId = x.AlbumId,
                AlbumTitle = x.AlbumTitle,
                PositionIndex = x.PositionIndex
            }).ToList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Reorder(ReorderAlbumGroupViewModel model)
        {
            try
            {
                List<int> orderedAlbumIdList = model.Items.OrderBy(x => x.PositionIndex).Select(x => x.AlbumId).ToList();
                await _albumGroupRepo.SetOrderedAlbumListAsync(model.GroupId, orderedAlbumIdList);
                this.SetBootstrapPageAlert("Success", "Album group reordered", BootstrapAlertType.success);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                _log.LogError(e, "Error reordering album group");
                this.SetBootstrapPageAlert("Error", "Error reordering album group", BootstrapAlertType.success);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public IActionResult Add()
        {
            CreateAlbumGroupViewModel model = new CreateAlbumGroupViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateAlbumGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _albumGroupRepo.AddAsync(new AlbumGroup
                    {
                        Key = model.Key,
                        Name = model.Name
                    });
                    this.SetBootstrapPageAlert("Success", "Album group added", BootstrapAlertType.success);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    if(e is RepositoryException)
                    {
                        ModelState.AddModelError(nameof(model.Key), e.Message);
                    }
                    else
                    {
                        ModelState.AddModelError(nameof(model.Key), "Unknown error");
                        _log.LogError("AddAlbumGroup", e, "Error adding group");
                    }
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            EditAlbumGroupViewModel model = new EditAlbumGroupViewModel();
            var result = await _albumGroupRepo.GetAsync(id);
            if(result != null)
            {
                model.Key = result.Key;
                model.Name = result.Name;
                return View(model);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditAlbumGroupViewModel model)
        {
            AlbumGroupDetail group = await _albumGroupRepo.GetAsync(model.Id);
            if (group != null)
            {

                model.Key = group.Key; // key cant be overwritten
                if (ModelState.IsValid)
                {
                    try { 
                        group.Name = model.Name;
                    
                        await _albumGroupRepo.UpdateAsync(model.Id, group);
                        this.SetBootstrapPageAlert("Success", "Album group updated", BootstrapAlertType.success);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception e)
                    {
                        if (e is RepositoryException)
                        {
                            ModelState.AddModelError(nameof(model.Key), e.Message);
                        }
                        else
                        {
                            ModelState.AddModelError(nameof(model.Key), "Unknown error");
                            _log.LogError("EditAlbumGroup", e, "Error updating group");
                        }
                        return View(model);
                    }
                }
                else
                {
                    return View(model);
                }
            }
            else
            {
                // todo: show error message
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View();
        }
    }
}

src/AdminSite/Views/AlbumGroup/Add.cshtml
@model CreateAlbumGroupViewModel
@{
    ViewData["Title"] = "Add group";
}


<h2>Add album group</h2>


<form asp-action="Add" asp-controller="AlbumGroup" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
        <label asp-for="Key" class=" col-md-2 col-form-label">Key</label>
        <div class="col-md-10">
            <input asp-for="Key" placeholder="Group key" />
            <span asp-validation-for="Key" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Name" class=" col-md-2 col-form-label">Name</label>
        <div class="col-md-10">
            <input asp-for="Name" placeholder="Group name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2"></div>
        <div class="col-md-10">
            <button type="submit" class="btn btn-primary">Add group</button>
            <a asp-action="index" class="btn btn-default">Cancel</a>
        </div>
    </div>
</form>

src/AdminSite/Views/AlbumGroup/Edit.cshtml
@model EditAlbumGroupViewModel
@{
    ViewData["Title"] = "Edit group";
}

<h2>Edit album group</h2>


<form asp-action="Edit" asp-controller="AlbumGroup" enctype="multipart/form-data">
    <input type="hidden" asp-for="Id" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
        <label asp-for="Key" class=" col-md-2 col-form-label">Key</label>
        <div class="col-md-10">
            <input asp-for="Key" readonly="readonly" placeholder="Group key" />
            <span asp-validation-for="Key" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Name" class=" col-md-2 col-form-label">Name</label>
        <div class="col-md-10">
            <input asp-for="Name" placeholder="Group name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2"></div>
        <div class="col-md-10">
            <button type="submit" class="btn btn-primary">Update group</button>
            <a asp-action="index" class="btn btn-default">Cancel</a>
        </div>
    </div>
</form>

src/AdminSite/Views/AlbumGroup/Index.cshtml
@model AlbumGroupIndexPageViewModel
@{
    ViewData["Title"] = "Manage groups";
}


<div class="container page-header-container">
    <div class="row">
        <div class="col-md-8">
            <h2>Manage album groups</h2>
        </div>
        <div class="col-md-4">
            <a asp-action="Add" class="btn btn-primary pull-right">Add group</a>
        </div>
    </div>
</div>



<div class="container index-list">
    <div class="row header">
        <div class="col-md-3">Key</div>
        <div class="col-md-2">Name</div>
        <div class="col-md-2">Updated</div>
        <div class="col-md-2">Items</div>
        <div class="col-md-3"></div>
    </div>
    @foreach(var i in Model.Items)
    {
    <div class="row">
        <div class="col-md-3">@i.Key</div>
        <div class="col-md-2">@i.Name</div>
        <div class="col-md-2">@i.Updated</div>
        <div class="col-md-2">@i.TotalAlbums</div>
        <div class="col-md-3">
            <div class="action-links">
                <a asp-action="edit" asp-route-id="@i.Id" class="btn btn-primary btn-xs">edit</a>
                <a asp-action="reorder" asp-route-id="@i.Id" class="btn btn-primary btn-xs">reorder</a>
                <button type="submit" class="btn btn-danger btn-xs" asp-action="Delete" asp-route-id="@i.Id">delete</button>
            </div>
        </div>
    </div>
    }
</div>

src/AdminSite/Views/AlbumGroup/Reorder.cshtml
@model ReorderAlbumGroupViewModel
@{
    ViewData["Title"] = "Reorder group";
}

<h2>Reorder group @Model.GroupName</h2>


<form asp-action="Reorder" asp-controller="AlbumGroup">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="GroupId" />

    <div class="container reorder-albums-list index-list">
        @for (int i = 0; i < Model.Items.Count; i++)
        {
            <div class="row reorder-row">
                <div class="col-md-10">

                    <input type="hidden" asp-for="Items[i].AlbumId" class="item-id postback-input" />
                    <input type="hidden" asp-for="Items[i].PositionIndex" class="item-index postback-input" />
                    <span>@Model.Items[i].AlbumTitle</span>

                </div>
                <div class="col-md-2">
                    <button type="button" class="sort-button btn btn-xs btn-default" tabindex="-1">drag to sort</button>
                </div>
            </div>

        }
    </div>
    <div class="container">
        <div class="row buttons-row">
            <button class="add-track-btn btn btn-primary" type="submit">Update order</button>
            <a asp-action="index" class="btn btn-default">Cancel</a>
        </div>
    </div>
</form>



@section Scripts{

<script>
        $(function(){
            // allow drag and drop sorting of the list
            $('.reorder-albums-list').reorderPostbackList();
        });
</script>
}